name: Sync Fork Automatically

on:
  schedule:
    - cron: '0 0 * * *' # ירוץ אוטומטית בכל יום בחצות
  workflow_dispatch: # מאפשר לך להריץ את זה גם ידנית בלחיצת כפתור מה-Actions

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sync upstream changes
        run: gh repo sync $REPOSITORY -b main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
